# Generated by Django 3.0.5 on 2020-06-15 21:23

from django.db import migrations, models
import examinations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_auto_20200614_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressureexamination',
            name='diastole',
            field=models.PositiveSmallIntegerField(validators=[examinations.validators.validate_diastole_range], verbose_name='Ciśnienie Rozkurczowe'),
        ),
        migrations.AlterField(
            model_name='pressureexamination',
            name='systole',
            field=models.PositiveSmallIntegerField(validators=[examinations.validators.validate_systole_range], verbose_name='Ciśnienie Skurczowe'),
        ),
        migrations.AlterField(
            model_name='pulseexamination',
            name='pulse',
            field=models.PositiveSmallIntegerField(validators=[examinations.validators.validate_pulse_range], verbose_name='Tętno'),
        ),
        migrations.AlterField(
            model_name='temperatureexamination',
            name='temperature',
            field=models.DecimalField(decimal_places=1, error_messages={'invalid': 'your custom error message'}, max_digits=3, verbose_name='Temperatura'),
        ),
    ]
